### ISSUE TITLE
Next prompt time not working correctly. 

### ISSUE THREAD

**Issue by willdadrummer** [mpanighetti/install-or-defer#23]
When I change the time till next prompt it shows correct in the console, but does not run. It just says will appear after "date" and never does anything.

**Comment by willdadrummer** [comment]
It does actually seem to be re-prompting, but it is random.

**Comment by homebysix** [comment]
Hi @willdadrummer - When you say "time till next prompt", which specific variable are you changing and where? There are options to set some variables in the script itself, and options to set some variables in a plist or configuration profile.

By default, the launchdaemon is configured to re-run the script every 20 minutes. As long as you're seeing the prompt appear within 20 minutes after the `DEFERRED_UNTIL` time, it's expected behavior. If the prompt timing is truly random for you, that would be something I haven't yet seen in testing.

**Comment by mpanighetti** [comment]
@willdadrummer Are you still seeing this behavior in the latest build? If so, please let us know exactly which variables you're changing in which parts of the script. Thanks!

**Comment by mpanighetti** [comment]
Closing this out, but if you still encounter this issue with an unmodified copy of the latest release, let us know in a new issue and we can follow up.

**Comment by willdadrummer** [comment]
Hey Mario, thanks for responding. I was let go so I am not sure if they are
still having that issue.
