### ISSUE TITLE
Mojave - Update downloaded but didn't install

### ISSUE THREAD

**Issue by master-vodawagner** [mpanighetti/install-or-defer#40]
I've got a user who advised the latest security update for macOS Mojave has been hanging using the v3.0 of install or defer.

I couldn't find anything in the logs to indicate why though, the logs say it was downloading it then it was downloaded and finally the user clicked run update.

Thu Feb  6 11:33:34 GMT 2020: Start of preinstall script…
Thu Feb  6 11:33:34 GMT 2020: Killing any active jamfHelper notifications...
Removing existing script resources...
Deleted file: //Library/Preferences/<REDACTED>
Deleted file: //private/tmp/install-or-defer
Thu Feb  6 11:33:34 GMT 2020: End of preinstall script…
Thu Feb  6 11:33:35 GMT 2020: Starting install-or-defer.sh script. Performing validation and error checking...
Thu Feb  6 11:33:36 GMT 2020: Validation and error checking passed. Starting main process...
Thu Feb  6 11:33:37 GMT 2020: Max deferral time undefined, or not set to a positive integer. Using default value.
Thu Feb  6 11:33:37 GMT 2020: Maximum deferral time: 72h:00m:00s
Thu Feb  6 11:33:37 GMT 2020: Deferral deadline: 2020-02-09 11:33:37
Thu Feb  6 11:33:37 GMT 2020: Time remaining: 72h:00m:00s
Thu Feb  6 11:33:37 GMT 2020: Checking for pending system updates...
Thu Feb  6 11:34:47 GMT 2020: Caching all system updates...
Thu Feb  6 11:34:47 GMT 2020:  Software Update Tool Finding available software Downloading Security Update Developer Beta 2020-002 Downloaded Security Update Developer Beta 2020-002 Done.
Thu Feb  6 11:36:21 GMT 2020: Prompting to install updates now or defer...
Thu Feb  6 11:36:27 GMT 2020: User clicked Run Updates after 00h:00m:06s.
Thu Feb  6 11:36:27 GMT 2020: Running all system updates...

Is there any additional logging I can look at?

**Comment by mpanighetti** [comment]
I'd take a look at the `softwareupdate` process in the system log to see what's holding it up. For what it's worth, I've successfully tested this build on a Mojave VM running the latest security update and confirmed it was able to progress to the restart phase.

Also worth noting: the logs report that this Mac was running a beta release (Security Update Developer Beta 2020-002), which might explain things not working as expected. Try removing the Mac from the beta program and running the normal release of this security update, and see if that goes through successfully.

**Comment by jimgrice** [comment]
We are following this on our site as we had about 5 failures, and not all Mojave. Some High Sierra and some Catalina. Not sure this is because of beta. Running the raw code in your script in a terminal failed to trigger the software update REBOOT as noted in the original ticket. I would encourage you to take a look to see if Apple has changed how restarts are triggered. Thanks for a great product!

**Comment by master-vodawagner** [comment]
So II just had a Catalina machine stuck at the same point for over an hour but as soon as I killed the PID for softwareupdate --install --$INSTALL_WHICH --no-scan 2>&1 the machine rebooted to start the install

**Comment by mpanighetti** [comment]
Doesn't seem like there's been any change in restart behavior since the most recent script revisions and macOS releases. Recommend trying again with [v3.0.1](https://github.com/mpanighetti/install-or-defer/releases/tag/v3.0.1), which improves the cleanup steps in a reinstall workflow and may help better reset an environment running v3.0 and running into issues.

**Comment by jimgrice** [comment]
Thanks, we found the issue on our end. Many months ago. Cheers!

--
On hackney'd steeds, the giddy blockheads fly.
