### ISSUE TITLE
Timer issue 

### ISSUE THREAD

**Issue by mani2care** [mpanighetti/install-or-defer#53]
1)My suggestion use the live timer how many days, hours, and seconds in the clock 

so we aware that timing is running in end users. just giving in windows after 1 hr the current timing will not show its shows only the same timing as its.

2) store the downloading log to someplace and try to show it while downloading the patches so the user will aware its downloading or not 

3) after killing all application give the full-screen windows and ask the user to reboot the machine with timer for 5 min if the user not rebooted then schedule the auto-reboot then open is make sense.

**Comment by mpanighetti** [comment]
If you know how to make `jamfHelper` display a live countdown, that would be a welcome contribution to the project, but as I understand it, that process can only display static text in the description box and doesn't support a live timer.

**Comment by mani2care** [comment]
Find the link for a more advanced process with timer and final reminder windows 
https://babodee.wordpress.com/2021/03/30/handling-major-upgrades-and-minor-updates-for-macos-with-jamf/

**Comment by mpanighetti** [comment]
Thanks for passing that on! We should be able to incorporate a timeout countdown for the final `display_act_msg` alert before updates are kicked off automatically. Would be worth revisiting that function in general, as jamfHelper natively supports a timeout without needing to be wrapped in a LaunchDaemon, so that could simplify the script logic a bit. I'll test this change in my own environment and pass an update over if it works well.

**Comment by mpanighetti** [comment]
The final countdown timer seems like a good addition in my testing, will set up a pull request shortly. I wanted to check on your other requests.

The script already sends logs to the system log via `logger`; you can see the live output by filtering for `logger` processes in Console ([more info on the readme](https://github.com/mpanighetti/install-or-defer#testing)). While the updates are running in the background, [the script displays a relevant alert](https://github.com/mpanighetti/install-or-defer/blob/main/img/running-updates.png) indicating background activity. I'm not sure what value there would be in displaying raw log output, and since these alerts don't have the ability to display dynamic text, it would likely require excessive alert killing and respawning and make that status alert much more complicated to script.

As for displaying another alert after closing applications but before restarting, this feels like an unnecessary extra step. Once the apps have been closed, the desired outcome would be an immediate restart, so any intermediate popup would delay the restart further, and give people a chance to reopen closed applications and attempt to resume work.

I don't think I'll be pursuing these other requests, but I'm open to hearing more thoughts from you on what value they would provide and how you'd want them implemented.

**Comment by mpanighetti** [comment]
Countdown timer has been implemented on the final alert before update enforcement as v4.1.2 in #55. Thanks for the suggestion!
