### ISSUE TITLE
Custom Log File

### ISSUE THREAD

**Issue by adonboli** [mpanighetti/install-or-defer#63]
It would be great if we could specify a custom log file to be created for this, so it is not logging in the system itself and that way the log can be kept on the computer in case there is a need to review it later to find what might have gone wrong.

**Comment by K3ll3r** [comment]
@adonboli I actually had created a fork a while back that did this. I've since moved back to the default behavior (using logger to output to the system log), but all you would need to do is replace [the first code block under "Validation and Error Checking"](https://github.com/mpanighetti/install-or-defer/blob/2a7522d38341d1414259f50c789ba795a70d403c/payload/Library/Scripts/Install%20or%20Defer.sh#L387-L389) with the following:

```
# Copy all output to the system log for diagnostic purposes.
if [[ ! -d "/var/log/install_or_defer_logs" ]]; then
   echo "log directory does not exist. Creating."
   /bin/mkdir "/var/log/install_or_defer_logs"
fi
exec 1>/var/log/install_or_defer_logs/install_or_defer_`date '+%Y%m%d_%H%M%S'`.log 2>&1
echo "Starting $(/usr/bin/basename "$0"). Performing validation and error checking..."
```

The code above creates a directory (var/log/install_or_defer_logs/) and then creates a log file with the date every time it runs.

**Comment by mpanighetti** [comment]
Nicely done! I imagine we could wrap that into an optional config profile flag to change default output behavior. Currently working on bringing in some other changes from my local copy of the project but I'll work on implementing this soon.

**Comment by mpanighetti** [comment]
Added static log output support in [version 5.0](https://github.com/mpanighetti/install-or-defer/releases/tag/v5.0)! Just create a configuration profile and set `DiagnosticLog` to `true` (see README for config profile details). Thanks for the suggestion!
