### ISSUE TITLE
Additional updates are prompted after updating the OS

### ISSUE THREAD

**Issue by vinulogy** [mpanighetti/install-or-defer#66]
I'm not sure if this is an expected behaviour, but here goes. After users update their OS, they receive another prompt to install the "Device Support" update. (This was on Catalina 10.15.7)

Some users feel they're stuck in an update loop. Is it possible to combine the Device Support with the OS update? 

<img width="473" alt="Screen Shot 2021-11-01 at 10 48 16 AM" src="https://user-images.githubusercontent.com/38265326/139692638-9297006b-374b-4262-bbb4-d5a28eadf179.png">

**Comment by mpanighetti** [comment]
Unfortunately, if an update requires running a previous update, then you'll potentially get another alert after running the first update, and they cannot be combined since the secondary update isn't advertised to the system when it runs `softwareupdate --list` initially. The same thing would happen if they manually ran updates in System Preferences > Software Update; they'd get a security update, run it, restart, then get another prompt to install the secondary update. This behavior is called out as a limitation [on the README](https://github.com/mpanighetti/install-or-defer#limitations).

If multiple updates are available when `softwareupdate --list` is run and finds a restart-required update, the script will run all available updates, so as far as I know it's already doing about all it can do to minimize this behavior. If Apple keeps making Device Support Updates require having already run security updates and restarted, this behavior will likely persist in the future.

Hope that all helps! Let me know if you have any other questions about how the script functions on the backend, always happy to look for opportunities to improve. I already see from your screenshot that we could use some logic around updates with no version number included. :D
