### ISSUE TITLE
LaunchDaemon shows as bash in Ventura login Items

### ISSUE THREAD

**Issue by master-vodawagner** [mpanighetti/install-or-defer#91]
Not sure if its possible or not but a more friendly name for the LaunchDaemon would be great when macOS Ventura rolls out.

Currently the LD shows up as "bash" in System Settings > General > Login Items

**Comment by mpanighetti** [comment]
Looks like the reason `bash` is the label is because it's the first entry under `ProgramArguments` in the LaunchDaemon:

https://github.com/mpanighetti/install-or-defer/blob/1fc6ae619909f75101e4d56491fadf963dc721b7/payload/Library/LaunchDaemons/com.github.mpanighetti.install-or-defer.plist#L7-L11

If we replace the `ProgramArguments` array with a single `Program` key pointed at the script, I believe that would change the label, hopefully to use the `Label` string. Would need to test this in a Ventura install.

**Comment by mpanighetti** [comment]
@master-vodawagner give #92 a try in your macOS Ventura test environment, let me know how it appears in System Settings > General > Login Items.

**Comment by mpanighetti** [comment]
Confirmed on my system (macOS 12.6-arm64) that the LaunchDaemon loads normally when the script is called as a `Program` rather than as `ProgramArguments`.

**Comment by mpanighetti** [comment]
Ran Install or Defer on macOS 13.0 (22A380) and it now displays a much nicer `Install or Defer.sh` in Login Items. Looks like this user experience was improved since the beta builds, so I don't think any action is required here, but I'll go ahead and merge #92 since it brings additional script improvements. Thanks for testing!
