### ISSUE TITLE
validate macOS Ventura compatibility

### ISSUE THREAD

**Issue by mpanighetti** [mpanighetti/install-or-defer#93]
Now that macOS Ventura is out of beta, need to validate that this script works as expected from that environment, including reliable update availability reporting and potentially successful update installation. Once that's done, I'll push an updated build removing the Ventura block.

**Comment by eltonajmenezes** [comment]
FYI: I was testing this script on Ventura and it doesn't seem to work as intended as on Monterrey

**Comment by justintrant** [comment]
Wondering if there's an ETA for an official release of v6.0?

**Comment by mpanighetti** [comment]
I've been testing the update in the [ventura branch](https://github.com/mpanighetti/install-or-defer/tree/ventura), feel free to try it out and report back!

**Comment by justintrant** [comment]
No issues so far, it works great! For Monterey clients, Ventura is hidden in the list of prompted updates, and it works as expected on Ventura (have tested both Apple Silicon and Intel Macs).

The usual caveats apply but we have trained our users to reboot and manually install updates, should Install or Defer not do so automatically due to the issues around _softwareupdated_.

Thanks as always for your great work!
